http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
    proxyOptions: # https://github.com/http-party/node-http-proxy
      changeOrigin: true
  local:
    host: localhost
    methods: [ "GET", "OPTIONS", "PUT", "POST", "PATCH", "DELETE" ]
    paths: '/healthz'
    scopes:
      - read
      - write
      - delete
serviceEndpoints:
  httpbin:
    url: https://httpbin.org
  local:
    urls:
      - http://localhost:3002
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - log: # policy name
          - action: # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} # parameter for log action
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true

  local:
    apiEndpoints:
      - local
    policies:
      - log: # policy name
          - action: # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} # parameter for log action
      - proxy:
          - action:
              serviceEndpoint: local
              changeOrigin: true
