http:
  port: 9513
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
    proxyOptions: # https://github.com/http-party/node-http-proxy
      changeOrigin: true
  cats:
    host: localhost
    methods: 'GET,OPTIONS,HEAD,PUT,PATCH,POST,DELETE' # [ "GET", "OPTIONS", "PUT", "POST", "PATCH", "DELETE" ]
    paths: '/cats*'
    scopes:
      - read
      - write
      - delete
  coffee:
    host: localhost
    methods: 'GET,OPTIONS,HEAD,PUT,PATCH,POST,DELETE' # [ "GET", "OPTIONS", "PUT", "POST", "PATCH", "DELETE" ]
    paths: '/coffee*'
    scopes:
      - read
      - write
      - delete
serviceEndpoints:
  httpbin:
    url: https://httpbin.org
  cats:
    urls: # 负载平衡策略，循环请求
      - http://localhost:4001
  coffee:
    urls:
      - http://localhost:4002
policies:
  - basic-auth
  - cors
  - expression # 启用表达式，执行任意JavaScript代码
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - request-transformer
  - response-transformer
  - rewrite
#  - terminate # 终止api
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - log: # policy name
          - action: # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} # parameter for log action
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  cats:
    apiEndpoints:
      - cats
    policies:
      - rewrite: # 添加重定向
          - condition:
              name: pathmatch
              match: /cats/:code
            action:
              rewrite: /cats/v1/:code
              redirect: 302
          - condition:
              name: regexpmatch
              match: ^/js/(.*)$
            action:
              rewrite: /src/js/$1
      - request-transformer:
          - action:
              body:
                add:
                  hello: req.query.id
              headers:
                add:
                  r-test: req.query.id || '32'
      - response-transformer:
          - action:
              body:
                add:
                  hello: "'world'"
              headers:
                add:
                  r-test: "'header value'"
      - rate-limit: # 限制频次
          - action:
              max: 3 # 最大请求多少次
              windowMs: 1000 # 每隔多少毫秒
              rateLimitBy: "${req.hostname}" # 筛选
              message: "请求太频繁，请稍后重试"
              statusCode: 429 # 超出最大值时返回状态码
      - log: # policy name
          - action: # array of condition/actions objects
              message: '${req.method} ${req.originalUrl}' # parameter for log action
#      - terminate:
#          statusCode: 401
#          message: '已下线'
      - proxy:
          - action:
              serviceEndpoint: cats
              changeOrigin: true
  coffee:
    apiEndpoints:
      - coffee
    policies:
#      - basic-auth:
      - expression:
          - action:
              jscode: 'req.url = req.url + "&x=2"'
      - cors: # 其实配置的是：Access-Control-Allow-Origin 属性
          - action:
              origin: 'localhost'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
      - rewrite: # 添加重定向
          - condition:
              name: pathmatch
              match: /coffee/:route # 多段匹配?
            action:
              rewrite: /coffee/v1/:route
              redirect: 302
          - condition:
              name: regexpmatch
              match: ^/js/(.*)$
            action:
              rewrite: /src/js/$1
      - log: # policy name
          - action: # array of condition/actions objects
              message: '${req.method} ${req.originalUrl}' # parameter for log action
      - proxy:
          - action:
              serviceEndpoint: coffee
              changeOrigin: true
